# Generated by Django 3.1.3 on 2020-11-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
