# Generated by Django 3.1.3 on 2020-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0004_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'upload_document',
                'managed': False,
            },
        ),
    ]
